//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

using hasoftware.Cdef;

namespace hasoftware.Api {
   public class FunctionCode : CdefFunctionCode {
      public const int Error = 0x0000;
      public const int Heartbeat = 0x0001;
      public const int Notify = 0x0002;
      public const int InputMessage = 0x1000;
      public const int OutputMessage = 0x1001;
      public const int Login = 0x1002;
      public const int OutputDevice = 0x1004;
      public const int Location = 0x1005;
      public const int Point = 0x1006;
      public const int CurrentEvent = 0x1007;
   }
}
