//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

using System;
using System.Collections.Generic;
using hasoftware.Cdef;
using hasoftware.Api;

namespace hasoftware.Classes {
   public class DeviceType {
      public int Id { get; set; }
      public string Code { get; set; }

      public DeviceType() {
      }

      public DeviceType(CdefMessage cdefMessage) {
         Id = cdefMessage.GetInt();
         Code = cdefMessage.GetString();
      }

      public void Encode(CdefMessage cdefMessage) {
         cdefMessage.PutInt(Id);
         cdefMessage.PutString(Code);
      }
   }
}
