//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

using System;
using System.Collections.Generic;
using hasoftware.Cdef;
using hasoftware.Api;

namespace hasoftware.Classes {
   public class ErrorMessage {
      public int Number { get; set; }
      public int Code { get; set; }
      public string Message { get; set; }

      public ErrorMessage() {
      }

      public ErrorMessage(CdefMessage cdefMessage) {
         Number = cdefMessage.GetInt();
         Code = cdefMessage.GetInt();
         Message = cdefMessage.GetString();
      }

      public void Encode(CdefMessage cdefMessage) {
         cdefMessage.PutInt(Number);
         cdefMessage.PutInt(Code);
         cdefMessage.PutString(Message);
      }
   }
}
