//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

using System;
using System.Collections.Generic;
using hasoftware.Cdef;
using hasoftware.Api;

namespace hasoftware.Classes {
   public class OutputMessage {
      public int Id { get; set; }
      public string DeviceTypeCode { get; set; }
      public string Data { get; set; }
      public long CreatedOn { get; set; }

      public OutputMessage() {
      }

      public OutputMessage(CdefMessage cdefMessage) {
         Id = cdefMessage.GetInt();
         DeviceTypeCode = cdefMessage.GetString();
         Data = cdefMessage.GetString();
         CreatedOn = cdefMessage.GetLong();
      }

      public void Encode(CdefMessage cdefMessage) {
         cdefMessage.PutInt(Id);
         cdefMessage.PutString(DeviceTypeCode);
         cdefMessage.PutString(Data);
         cdefMessage.PutLong(CreatedOn);
      }
   }
}
