//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

using System;
using System.Collections.Generic;
using hasoftware.Api;
using hasoftware.Classes;
using hasoftware.Cdef;

namespace hasoftware.Messages {
   public class CurrentEventRequest : Message {
      public int Action { get; set; }
      public List<int> Ids { get; set; }
      public List<CurrentEvent> CurrentEvents { get; set; }

      public CurrentEventRequest() {
         FunctionCode = Api.FunctionCode.CurrentEvent;
         Ids = new List<int>();
         CurrentEvents = new List<CurrentEvent>();
      }

      public CurrentEventRequest(CdefMessage cdefMessage) : base(cdefMessage) {
         Action = cdefMessage.GetInt();
         {
            Ids = new List<int>();
            int c = cdefMessage.GetInt();
            for (int i=0; i<c; i++) {
               Ids.Add(cdefMessage.GetInt());
            }
         }
         {
            CurrentEvents = new List<CurrentEvent>();
            int c = cdefMessage.GetInt();
            for (int i=0; i<c; i++) {
               CurrentEvents.Add(new CurrentEvent(cdefMessage));
            }
         }
      }

      public override void Encode(CdefMessage cdefMessage) {
         base.Encode(cdefMessage);
         cdefMessage.PutInt(Action);
         cdefMessage.PutInt(Ids.Count);
         foreach (var obj in Ids) {
            cdefMessage.PutInt(obj);
         }
         cdefMessage.PutInt(CurrentEvents.Count);
         foreach (var obj in CurrentEvents) {
            obj.Encode(cdefMessage);
         }
      }

      public CurrentEventResponse CreateResponse() {
         CurrentEventResponse response = new CurrentEventResponse(TransactionNumber);
         return response;
      }
   }
}
