//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

using System;
using System.Collections.Generic;
using hasoftware.Api;
using hasoftware.Classes;
using hasoftware.Cdef;

namespace hasoftware.Messages {
   public class ErrorResponse : Message {
      public List<ErrorMessage> ErrorMessages { get; set; }

      public ErrorResponse(int transactionNumber) : base(Api.FunctionCode.Error, transactionNumber, CdefSystemFlags.Response) {
         ErrorMessages = new List<ErrorMessage>();
      }

      public ErrorResponse(CdefMessage cdefMessage) : base(cdefMessage) {
         {
            ErrorMessages = new List<ErrorMessage>();
            int c = cdefMessage.GetInt();
            for (int i=0; i<c; i++) {
               ErrorMessages.Add(new ErrorMessage(cdefMessage));
            }
         }
      }

      public override void Encode(CdefMessage cdefMessage) {
         base.Encode(cdefMessage);
         cdefMessage.PutInt(ErrorMessages.Count);
         foreach (var obj in ErrorMessages) {
            obj.Encode(cdefMessage);
         }
      }
   }
}
