//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

using System;
using System.Collections.Generic;
using hasoftware.Api;
using hasoftware.Classes;
using hasoftware.Cdef;

namespace hasoftware.Messages {
   public class HeartbeatRequest : Message {
      public HeartbeatRequest() {
         FunctionCode = Api.FunctionCode.Heartbeat;
      }

      public HeartbeatRequest(CdefMessage cdefMessage) : base(cdefMessage) {
      }

      public override void Encode(CdefMessage cdefMessage) {
         base.Encode(cdefMessage);
      }

      public HeartbeatResponse CreateResponse() {
         HeartbeatResponse response = new HeartbeatResponse(TransactionNumber);
         return response;
      }
   }
}
