//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

using System;
using System.Collections.Generic;
using hasoftware.Api;
using hasoftware.Classes;
using hasoftware.Cdef;

namespace hasoftware.Messages {
   public class InputMessageRequest : Message {
      public int Action { get; set; }
      public List<int> Ids { get; set; }
      public List<InputMessage> InputMessages { get; set; }

      public InputMessageRequest() {
         FunctionCode = Api.FunctionCode.InputMessage;
         Ids = new List<int>();
         InputMessages = new List<InputMessage>();
      }

      public InputMessageRequest(CdefMessage cdefMessage) : base(cdefMessage) {
         Action = cdefMessage.GetInt();
         {
            Ids = new List<int>();
            int c = cdefMessage.GetInt();
            for (int i=0; i<c; i++) {
               Ids.Add(cdefMessage.GetInt());
            }
         }
         {
            InputMessages = new List<InputMessage>();
            int c = cdefMessage.GetInt();
            for (int i=0; i<c; i++) {
               InputMessages.Add(new InputMessage(cdefMessage));
            }
         }
      }

      public override void Encode(CdefMessage cdefMessage) {
         base.Encode(cdefMessage);
         cdefMessage.PutInt(Action);
         cdefMessage.PutInt(Ids.Count);
         foreach (var obj in Ids) {
            cdefMessage.PutInt(obj);
         }
         cdefMessage.PutInt(InputMessages.Count);
         foreach (var obj in InputMessages) {
            obj.Encode(cdefMessage);
         }
      }

      public InputMessageResponse CreateResponse() {
         InputMessageResponse response = new InputMessageResponse(TransactionNumber);
         return response;
      }
   }
}
