//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

using System;
using System.Collections.Generic;
using hasoftware.Api;
using hasoftware.Classes;
using hasoftware.Cdef;

namespace hasoftware.Messages {
   public class InputMessageResponse : Message {
      public int Action { get; set; }
      public List<InputMessage> InputMessages { get; set; }

      public InputMessageResponse(int transactionNumber) : base(Api.FunctionCode.InputMessage, transactionNumber, CdefSystemFlags.Response) {
         InputMessages = new List<InputMessage>();
      }

      public InputMessageResponse(CdefMessage cdefMessage) : base(cdefMessage) {
         Action = cdefMessage.GetInt();
         {
            InputMessages = new List<InputMessage>();
            int c = cdefMessage.GetInt();
            for (int i=0; i<c; i++) {
               InputMessages.Add(new InputMessage(cdefMessage));
            }
         }
      }

      public override void Encode(CdefMessage cdefMessage) {
         base.Encode(cdefMessage);
         cdefMessage.PutInt(Action);
         cdefMessage.PutInt(InputMessages.Count);
         foreach (var obj in InputMessages) {
            obj.Encode(cdefMessage);
         }
      }
   }
}
