//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

using System;
using System.Collections.Generic;
using hasoftware.Api;
using hasoftware.Classes;
using hasoftware.Cdef;

namespace hasoftware.Messages {
   public class LoginRequest : Message {
      public string Username { get; set; }
      public string Password { get; set; }

      public LoginRequest() {
         FunctionCode = Api.FunctionCode.Login;
      }

      public LoginRequest(CdefMessage cdefMessage) : base(cdefMessage) {
         Username = cdefMessage.GetString();
         Password = cdefMessage.GetString();
      }

      public override void Encode(CdefMessage cdefMessage) {
         base.Encode(cdefMessage);
         cdefMessage.PutString(Username);
         cdefMessage.PutString(Password);
      }

      public LoginResponse CreateResponse() {
         LoginResponse response = new LoginResponse(TransactionNumber);
         return response;
      }
   }
}
