//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

using System;
using System.Collections.Generic;
using hasoftware.Api;
using hasoftware.Classes;
using hasoftware.Cdef;

namespace hasoftware.Messages {
   public class NotifyRequest : Message {
      public List<int> FunctionCodes { get; set; }

      public NotifyRequest() {
         FunctionCode = Api.FunctionCode.Notify;
         FunctionCodes = new List<int>();
      }

      public NotifyRequest(CdefMessage cdefMessage) : base(cdefMessage) {
         {
            FunctionCodes = new List<int>();
            int c = cdefMessage.GetInt();
            for (int i=0; i<c; i++) {
               FunctionCodes.Add(cdefMessage.GetInt());
            }
         }
      }

      public override void Encode(CdefMessage cdefMessage) {
         base.Encode(cdefMessage);
         cdefMessage.PutInt(FunctionCodes.Count);
         foreach (var obj in FunctionCodes) {
            cdefMessage.PutInt(obj);
         }
      }

      public NotifyResponse CreateResponse() {
         NotifyResponse response = new NotifyResponse(TransactionNumber);
         return response;
      }
   }
}
