//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

using System;
using System.Collections.Generic;
using hasoftware.Api;
using hasoftware.Classes;
using hasoftware.Cdef;

namespace hasoftware.Messages {
   public class OutputDeviceResponse : Message {
      public int Action { get; set; }
      public List<OutputDevice> OutputDevices { get; set; }

      public OutputDeviceResponse(int transactionNumber) : base(Api.FunctionCode.OutputDevice, transactionNumber, CdefSystemFlags.Response) {
         OutputDevices = new List<OutputDevice>();
      }

      public OutputDeviceResponse(CdefMessage cdefMessage) : base(cdefMessage) {
         Action = cdefMessage.GetInt();
         {
            OutputDevices = new List<OutputDevice>();
            int c = cdefMessage.GetInt();
            for (int i=0; i<c; i++) {
               OutputDevices.Add(new OutputDevice(cdefMessage));
            }
         }
      }

      public override void Encode(CdefMessage cdefMessage) {
         base.Encode(cdefMessage);
         cdefMessage.PutInt(Action);
         cdefMessage.PutInt(OutputDevices.Count);
         foreach (var obj in OutputDevices) {
            obj.Encode(cdefMessage);
         }
      }
   }
}
