//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

using System;
using System.Collections.Generic;
using hasoftware.Api;
using hasoftware.Classes;
using hasoftware.Cdef;

namespace hasoftware.Messages {
   public class OutputMessageResponse : Message {
      public int Action { get; set; }
      public List<OutputMessage> OutputMessages { get; set; }

      public OutputMessageResponse(int transactionNumber) : base(Api.FunctionCode.OutputMessage, transactionNumber, CdefSystemFlags.Response) {
         OutputMessages = new List<OutputMessage>();
      }

      public OutputMessageResponse(CdefMessage cdefMessage) : base(cdefMessage) {
         Action = cdefMessage.GetInt();
         {
            OutputMessages = new List<OutputMessage>();
            int c = cdefMessage.GetInt();
            for (int i=0; i<c; i++) {
               OutputMessages.Add(new OutputMessage(cdefMessage));
            }
         }
      }

      public override void Encode(CdefMessage cdefMessage) {
         base.Encode(cdefMessage);
         cdefMessage.PutInt(Action);
         cdefMessage.PutInt(OutputMessages.Count);
         foreach (var obj in OutputMessages) {
            obj.Encode(cdefMessage);
         }
      }
   }
}
