//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

using System;
using System.Collections.Generic;
using hasoftware.Api;
using hasoftware.Classes;
using hasoftware.Cdef;

namespace hasoftware.Messages {
   public class PointRequest : Message {
      public int Action { get; set; }
      public int NodeId { get; set; }
      public string Address { get; set; }

      public PointRequest() {
         FunctionCode = Api.FunctionCode.Point;
      }

      public PointRequest(CdefMessage cdefMessage) : base(cdefMessage) {
         Action = cdefMessage.GetInt();
         NodeId = cdefMessage.GetInt();
         Address = cdefMessage.GetString();
      }

      public override void Encode(CdefMessage cdefMessage) {
         base.Encode(cdefMessage);
         cdefMessage.PutInt(Action);
         cdefMessage.PutInt(NodeId);
         cdefMessage.PutString(Address);
      }

      public PointResponse CreateResponse() {
         PointResponse response = new PointResponse(TransactionNumber);
         return response;
      }
   }
}
