//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

using System;
using System.Collections.Generic;
using hasoftware.Api;
using hasoftware.Classes;
using hasoftware.Cdef;

namespace hasoftware.Messages {
   public class PointResponse : Message {
      public int Action { get; set; }
      public List<Point> Points { get; set; }

      public PointResponse(int transactionNumber) : base(Api.FunctionCode.Point, transactionNumber, CdefSystemFlags.Response) {
         Points = new List<Point>();
      }

      public PointResponse(CdefMessage cdefMessage) : base(cdefMessage) {
         Action = cdefMessage.GetInt();
         {
            Points = new List<Point>();
            int c = cdefMessage.GetInt();
            for (int i=0; i<c; i++) {
               Points.Add(new Point(cdefMessage));
            }
         }
      }

      public override void Encode(CdefMessage cdefMessage) {
         base.Encode(cdefMessage);
         cdefMessage.PutInt(Action);
         cdefMessage.PutInt(Points.Count);
         foreach (var obj in Points) {
            obj.Encode(cdefMessage);
         }
      }
   }
}
