//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 3:02:01 PM
//

#ifndef FUNCTIONCODES_H
#define FUNCTIONCODES_H

namespace hasoftware {
   enum FunctionCode {
      InputMessage = 0x1000,
      OutputMessage = 0x1001,
      Login = 0x1002,
      OutputDevice = 0x1004,
      Location = 0x1005,
      Point = 0x1006,
      CurrentEvent = 0x1007,
   };
}

#endif
