//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 3:02:01 PM
//

#ifndef MESSAGE_FACTORY_H
#define MESSAGE_FACTORY_H

#include "MessageBase.h"
#include "CdefMessage.h"

namespace hasoftware {
   class MessageFactory {
   public:
      static HASoftware::MessageBase* Decode(HASoftware::CdefMessage &cdefMessage);
    };
}

#endif
