//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

package hasoftware.api.classes;

import hasoftware.cdef.CDEFMessage;
import java.util.List;
import java.util.LinkedList;

public class CurrentEvent {
   private int _id;
   private Point _point;
   private long _createdOn;
   private long _updatedOn;

   public CurrentEvent() {
   }

   public CurrentEvent(CDEFMessage cdefMessage) {
      _id = cdefMessage.getInt();
      _point = new Point(cdefMessage);
      _createdOn = cdefMessage.getLong();
      _updatedOn = cdefMessage.getLong();
   }

   public void encode(CDEFMessage cdefMessage) {
      cdefMessage.putInt(_id);
      _point.encode(cdefMessage);
      cdefMessage.putLong(_createdOn);
      cdefMessage.putLong(_updatedOn);
   }

   public int getId() { return _id; }
   public void setId(int id) { _id = id; }

   public Point getPoint() { return _point; }
   public void setPoint(Point point) { _point = point; }

   public long getCreatedOn() { return _createdOn; }
   public void setCreatedOn(long createdOn) { _createdOn = createdOn; }

   public long getUpdatedOn() { return _updatedOn; }
   public void setUpdatedOn(long updatedOn) { _updatedOn = updatedOn; }
}
