//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.classes;

import hasoftware.cdef.CDEFMessage;
import java.util.List;
import java.util.LinkedList;

public class DeviceType {
   private int _id;
   private String _code;

   public DeviceType() {
   }

   public DeviceType(CDEFMessage cdefMessage) {
      _id = cdefMessage.getInt();
      _code = cdefMessage.getString();
   }

   public void encode(CDEFMessage cdefMessage) {
      cdefMessage.putInt(_id);
      cdefMessage.putString(_code);
   }

   public int getId() { return _id; }
   public void setId(int id) { _id = id; }

   public String getCode() { return _code; }
   public void setCode(String code) { _code = code; }
}
