//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.classes;

import hasoftware.cdef.CDEFMessage;
import java.util.List;
import java.util.LinkedList;

public class ErrorMessage {
   private int _number;
   private int _code;
   private String _message;

   public ErrorMessage() {
   }

   public ErrorMessage(CDEFMessage cdefMessage) {
      _number = cdefMessage.getInt();
      _code = cdefMessage.getInt();
      _message = cdefMessage.getString();
   }

   public void encode(CDEFMessage cdefMessage) {
      cdefMessage.putInt(_number);
      cdefMessage.putInt(_code);
      cdefMessage.putString(_message);
   }

   public int getNumber() { return _number; }
   public void setNumber(int number) { _number = number; }

   public int getCode() { return _code; }
   public void setCode(int code) { _code = code; }

   public String getMessage() { return _message; }
   public void setMessage(String message) { _message = message; }
}
