//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

package hasoftware.api.classes;

import hasoftware.cdef.CDEFMessage;
import java.util.List;
import java.util.LinkedList;

public class InputMessage {
   private int _id;
   private String _deviceTypeCode;
   private String _data;
   private long _createdOn;

   public InputMessage() {
   }

   public InputMessage(CDEFMessage cdefMessage) {
      _id = cdefMessage.getInt();
      _deviceTypeCode = cdefMessage.getString();
      _data = cdefMessage.getString();
      _createdOn = cdefMessage.getLong();
   }

   public void encode(CDEFMessage cdefMessage) {
      cdefMessage.putInt(_id);
      cdefMessage.putString(_deviceTypeCode);
      cdefMessage.putString(_data);
      cdefMessage.putLong(_createdOn);
   }

   public int getId() { return _id; }
   public void setId(int id) { _id = id; }

   public String getDeviceTypeCode() { return _deviceTypeCode; }
   public void setDeviceTypeCode(String deviceTypeCode) { _deviceTypeCode = deviceTypeCode; }

   public String getData() { return _data; }
   public void setData(String data) { _data = data; }

   public long getCreatedOn() { return _createdOn; }
   public void setCreatedOn(long createdOn) { _createdOn = createdOn; }
}
