//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

package hasoftware.api.classes;

import hasoftware.cdef.CDEFMessage;
import java.util.List;
import java.util.LinkedList;

public class Location {
   private int _id;
   private int _parentId;
   private String _name;
   private long _createdOn;
   private long _updatedOn;

   public Location() {
   }

   public Location(CDEFMessage cdefMessage) {
      _id = cdefMessage.getInt();
      _parentId = cdefMessage.getInt();
      _name = cdefMessage.getString();
      _createdOn = cdefMessage.getLong();
      _updatedOn = cdefMessage.getLong();
   }

   public void encode(CDEFMessage cdefMessage) {
      cdefMessage.putInt(_id);
      cdefMessage.putInt(_parentId);
      cdefMessage.putString(_name);
      cdefMessage.putLong(_createdOn);
      cdefMessage.putLong(_updatedOn);
   }

   public int getId() { return _id; }
   public void setId(int id) { _id = id; }

   public int getParentId() { return _parentId; }
   public void setParentId(int parentId) { _parentId = parentId; }

   public String getName() { return _name; }
   public void setName(String name) { _name = name; }

   public long getCreatedOn() { return _createdOn; }
   public void setCreatedOn(long createdOn) { _createdOn = createdOn; }

   public long getUpdatedOn() { return _updatedOn; }
   public void setUpdatedOn(long updatedOn) { _updatedOn = updatedOn; }
}
