//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.classes;

import hasoftware.cdef.CDEFMessage;
import java.util.List;
import java.util.LinkedList;

public class OutputDevice {
   private int _id;
   private String _name;
   private String _description;
   private String _address;
   private String _deviceTypeCode;
   private String _serialNumber;
   private long _createdOn;
   private long _updatedOn;

   public OutputDevice() {
   }

   public OutputDevice(CDEFMessage cdefMessage) {
      _id = cdefMessage.getInt();
      _name = cdefMessage.getString();
      _description = cdefMessage.getString();
      _address = cdefMessage.getString();
      _deviceTypeCode = cdefMessage.getString();
      _serialNumber = cdefMessage.getString();
      _createdOn = cdefMessage.getLong();
      _updatedOn = cdefMessage.getLong();
   }

   public void encode(CDEFMessage cdefMessage) {
      cdefMessage.putInt(_id);
      cdefMessage.putString(_name);
      cdefMessage.putString(_description);
      cdefMessage.putString(_address);
      cdefMessage.putString(_deviceTypeCode);
      cdefMessage.putString(_serialNumber);
      cdefMessage.putLong(_createdOn);
      cdefMessage.putLong(_updatedOn);
   }

   public int getId() { return _id; }
   public void setId(int id) { _id = id; }

   public String getName() { return _name; }
   public void setName(String name) { _name = name; }

   public String getDescription() { return _description; }
   public void setDescription(String description) { _description = description; }

   public String getAddress() { return _address; }
   public void setAddress(String address) { _address = address; }

   public String getDeviceTypeCode() { return _deviceTypeCode; }
   public void setDeviceTypeCode(String deviceTypeCode) { _deviceTypeCode = deviceTypeCode; }

   public String getSerialNumber() { return _serialNumber; }
   public void setSerialNumber(String serialNumber) { _serialNumber = serialNumber; }

   public long getCreatedOn() { return _createdOn; }
   public void setCreatedOn(long createdOn) { _createdOn = createdOn; }

   public long getUpdatedOn() { return _updatedOn; }
   public void setUpdatedOn(long updatedOn) { _updatedOn = updatedOn; }
}
