//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.classes;

import hasoftware.cdef.CDEFMessage;
import java.util.List;
import java.util.LinkedList;

public class Point {
   private int _id;
   private int _nodeId;
   private String _name;
   private String _address;
   private String _deviceTypeCode;
   private String _message1;
   private String _message2;
   private int _priority;
   private long _createdOn;
   private long _updatedOn;
   private List<OutputDevice> _outputDevices = new LinkedList<>();

   public Point() {
   }

   public Point(CDEFMessage cdefMessage) {
      _id = cdefMessage.getInt();
      _nodeId = cdefMessage.getInt();
      _name = cdefMessage.getString();
      _address = cdefMessage.getString();
      _deviceTypeCode = cdefMessage.getString();
      _message1 = cdefMessage.getString();
      _message2 = cdefMessage.getString();
      _priority = cdefMessage.getInt();
      _createdOn = cdefMessage.getLong();
      _updatedOn = cdefMessage.getLong();
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _outputDevices.add(new OutputDevice(cdefMessage));
         }
      }
   }

   public void encode(CDEFMessage cdefMessage) {
      cdefMessage.putInt(_id);
      cdefMessage.putInt(_nodeId);
      cdefMessage.putString(_name);
      cdefMessage.putString(_address);
      cdefMessage.putString(_deviceTypeCode);
      cdefMessage.putString(_message1);
      cdefMessage.putString(_message2);
      cdefMessage.putInt(_priority);
      cdefMessage.putLong(_createdOn);
      cdefMessage.putLong(_updatedOn);
      cdefMessage.putInt(_outputDevices.size());
      for (OutputDevice obj : _outputDevices) { obj.encode(cdefMessage); }
   }

   public int getId() { return _id; }
   public void setId(int id) { _id = id; }

   public int getNodeId() { return _nodeId; }
   public void setNodeId(int nodeId) { _nodeId = nodeId; }

   public String getName() { return _name; }
   public void setName(String name) { _name = name; }

   public String getAddress() { return _address; }
   public void setAddress(String address) { _address = address; }

   public String getDeviceTypeCode() { return _deviceTypeCode; }
   public void setDeviceTypeCode(String deviceTypeCode) { _deviceTypeCode = deviceTypeCode; }

   public String getMessage1() { return _message1; }
   public void setMessage1(String message1) { _message1 = message1; }

   public String getMessage2() { return _message2; }
   public void setMessage2(String message2) { _message2 = message2; }

   public int getPriority() { return _priority; }
   public void setPriority(int priority) { _priority = priority; }

   public long getCreatedOn() { return _createdOn; }
   public void setCreatedOn(long createdOn) { _createdOn = createdOn; }

   public long getUpdatedOn() { return _updatedOn; }
   public void setUpdatedOn(long updatedOn) { _updatedOn = updatedOn; }

   public List<OutputDevice> getOutputDevices() { return _outputDevices; }
   public void setOutputDevices(List<OutputDevice> outputDevices) { _outputDevices = outputDevices; }
}
