//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class CurrentEventRequest extends Message {
   private int _action;
   private List<Integer> _ids = new LinkedList<>();
   private List<CurrentEvent> _currentEvents = new LinkedList<>();

   public CurrentEventRequest() {
      super(FunctionCode.CurrentEvent, 0);
   }

   public CurrentEventRequest(CDEFMessage cdefMessage) {
      super(cdefMessage);
      _action = cdefMessage.getInt();
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _ids.add(cdefMessage.getInt());
         }
      }
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _currentEvents.add(new CurrentEvent(cdefMessage));
         }
      }
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_action);
      cdefMessage.putInt(_ids.size());
      for (Integer obj : _ids) {
         cdefMessage.putInt(obj);
      }
      cdefMessage.putInt(_currentEvents.size());
      for (CurrentEvent obj : _currentEvents) {
         obj.encode(cdefMessage);
      }
   }

   public CurrentEventResponse createResponse() {
      CurrentEventResponse response = new CurrentEventResponse(getTransactionNumber());
      return response;
   }

   public int getAction() { return _action; }
   public void setAction(int action) { _action = action; }

   public List<Integer> getIds() { return _ids; }
   public void setIds(List<Integer> ids) { _ids = ids; }

   public List<CurrentEvent> getCurrentEvents() { return _currentEvents; }
   public void setCurrentEvents(List<CurrentEvent> currentEvents) { _currentEvents = currentEvents; }
}
