//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class ErrorResponse extends Message {
   private List<ErrorMessage> _errorMessages = new LinkedList<>();

   public ErrorResponse(int transactionNumber) {
      super(FunctionCode.Error, transactionNumber, CDEFSystemFlags.Response);
   }

   public ErrorResponse(CDEFMessage cdefMessage) {
      super(cdefMessage);
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _errorMessages.add(new ErrorMessage(cdefMessage));
         }
      }
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_errorMessages.size());
      for (ErrorMessage obj : _errorMessages) {
         obj.encode(cdefMessage);
      }
   }

   public List<ErrorMessage> getErrorMessages() { return _errorMessages; }
   public void setErrorMessages(List<ErrorMessage> errorMessages) { _errorMessages = errorMessages; }
}
