//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class HeartbeatRequest extends Message {
   public HeartbeatRequest() {
      super(FunctionCode.Heartbeat, 0);
   }

   public HeartbeatRequest(CDEFMessage cdefMessage) {
      super(cdefMessage);
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
   }

   public HeartbeatResponse createResponse() {
      HeartbeatResponse response = new HeartbeatResponse(getTransactionNumber());
      return response;
   }
}
