//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class HeartbeatResponse extends Message {
   public HeartbeatResponse(int transactionNumber) {
      super(FunctionCode.Heartbeat, transactionNumber, CDEFSystemFlags.Response);
   }

   public HeartbeatResponse(CDEFMessage cdefMessage) {
      super(cdefMessage);
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
   }
}
