//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class InputMessageResponse extends Message {
   private int _action;
   private List<InputMessage> _inputMessages = new LinkedList<>();

   public InputMessageResponse(int transactionNumber) {
      super(FunctionCode.InputMessage, transactionNumber, CDEFSystemFlags.Response);
   }

   public InputMessageResponse(CDEFMessage cdefMessage) {
      super(cdefMessage);
      _action = cdefMessage.getInt();
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _inputMessages.add(new InputMessage(cdefMessage));
         }
      }
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_action);
      cdefMessage.putInt(_inputMessages.size());
      for (InputMessage obj : _inputMessages) {
         obj.encode(cdefMessage);
      }
   }

   public int getAction() { return _action; }
   public void setAction(int action) { _action = action; }

   public List<InputMessage> getInputMessages() { return _inputMessages; }
   public void setInputMessages(List<InputMessage> inputMessages) { _inputMessages = inputMessages; }
}
