//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class InputMessageRequest extends Message {
   private int _action;
   private List<Integer> _ids = new LinkedList<>();
   private List<InputMessage> _inputMessages = new LinkedList<>();

   public InputMessageRequest() {
      super(FunctionCode.InputMessage, 0);
   }

   public InputMessageRequest(CDEFMessage cdefMessage) {
      super(cdefMessage);
      _action = cdefMessage.getInt();
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _ids.add(cdefMessage.getInt());
         }
      }
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _inputMessages.add(new InputMessage(cdefMessage));
         }
      }
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_action);
      cdefMessage.putInt(_ids.size());
      for (Integer obj : _ids) {
         cdefMessage.putInt(obj);
      }
      cdefMessage.putInt(_inputMessages.size());
      for (InputMessage obj : _inputMessages) {
         obj.encode(cdefMessage);
      }
   }

   public InputMessageResponse createResponse() {
      InputMessageResponse response = new InputMessageResponse(getTransactionNumber());
      return response;
   }

   public int getAction() { return _action; }
   public void setAction(int action) { _action = action; }

   public List<Integer> getIds() { return _ids; }
   public void setIds(List<Integer> ids) { _ids = ids; }

   public List<InputMessage> getInputMessages() { return _inputMessages; }
   public void setInputMessages(List<InputMessage> inputMessages) { _inputMessages = inputMessages; }
}
