//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class LocationResponse extends Message {
   private int _action;
   private List<Location> _locations = new LinkedList<>();

   public LocationResponse(int transactionNumber) {
      super(FunctionCode.Location, transactionNumber, CDEFSystemFlags.Response);
   }

   public LocationResponse(CDEFMessage cdefMessage) {
      super(cdefMessage);
      _action = cdefMessage.getInt();
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _locations.add(new Location(cdefMessage));
         }
      }
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_action);
      cdefMessage.putInt(_locations.size());
      for (Location obj : _locations) {
         obj.encode(cdefMessage);
      }
   }

   public int getAction() { return _action; }
   public void setAction(int action) { _action = action; }

   public List<Location> getLocations() { return _locations; }
   public void setLocations(List<Location> locations) { _locations = locations; }
}
