//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class LocationRequest extends Message {
   private int _action;
   private int _parentId;

   public LocationRequest() {
      super(FunctionCode.Location, 0);
   }

   public LocationRequest(CDEFMessage cdefMessage) {
      super(cdefMessage);
      _action = cdefMessage.getInt();
      _parentId = cdefMessage.getInt();
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_action);
      cdefMessage.putInt(_parentId);
   }

   public LocationResponse createResponse() {
      LocationResponse response = new LocationResponse(getTransactionNumber());
      return response;
   }

   public int getAction() { return _action; }
   public void setAction(int action) { _action = action; }

   public int getParentId() { return _parentId; }
   public void setParentId(int parentId) { _parentId = parentId; }
}
