//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class LoginRequest extends Message {
   private String _username;
   private String _password;

   public LoginRequest() {
      super(FunctionCode.Login, 0);
   }

   public LoginRequest(CDEFMessage cdefMessage) {
      super(cdefMessage);
      _username = cdefMessage.getString();
      _password = cdefMessage.getString();
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putString(_username);
      cdefMessage.putString(_password);
   }

   public LoginResponse createResponse() {
      LoginResponse response = new LoginResponse(getTransactionNumber());
      return response;
   }

   public String getUsername() { return _username; }
   public void setUsername(String username) { _username = username; }

   public String getPassword() { return _password; }
   public void setPassword(String password) { _password = password; }
}
