//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class NotifyResponse extends Message {
   private int _notifyFunctionCode;
   private int _action;
   private List<Integer> _ids = new LinkedList<>();

   public NotifyResponse(int transactionNumber) {
      super(FunctionCode.Notify, transactionNumber, CDEFSystemFlags.Response);
   }

   public NotifyResponse(CDEFMessage cdefMessage) {
      super(cdefMessage);
      _notifyFunctionCode = cdefMessage.getInt();
      _action = cdefMessage.getInt();
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _ids.add(cdefMessage.getInt());
         }
      }
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_notifyFunctionCode);
      cdefMessage.putInt(_action);
      cdefMessage.putInt(_ids.size());
      for (Integer obj : _ids) {
         cdefMessage.putInt(obj);
      }
   }

   public int getNotifyFunctionCode() { return _notifyFunctionCode; }
   public void setNotifyFunctionCode(int notifyFunctionCode) { _notifyFunctionCode = notifyFunctionCode; }

   public int getAction() { return _action; }
   public void setAction(int action) { _action = action; }

   public List<Integer> getIds() { return _ids; }
   public void setIds(List<Integer> ids) { _ids = ids; }
}
