//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class NotifyRequest extends Message {
   private List<Integer> _functionCodes = new LinkedList<>();

   public NotifyRequest() {
      super(FunctionCode.Notify, 0);
   }

   public NotifyRequest(CDEFMessage cdefMessage) {
      super(cdefMessage);
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _functionCodes.add(cdefMessage.getInt());
         }
      }
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_functionCodes.size());
      for (Integer obj : _functionCodes) {
         cdefMessage.putInt(obj);
      }
   }

   public NotifyResponse createResponse() {
      NotifyResponse response = new NotifyResponse(getTransactionNumber());
      return response;
   }

   public List<Integer> getFunctionCodes() { return _functionCodes; }
   public void setFunctionCodes(List<Integer> functionCodes) { _functionCodes = functionCodes; }
}
