//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class OutputMessageResponse extends Message {
   private int _action;
   private List<OutputMessage> _outputMessages = new LinkedList<>();

   public OutputMessageResponse(int transactionNumber) {
      super(FunctionCode.OutputMessage, transactionNumber, CDEFSystemFlags.Response);
   }

   public OutputMessageResponse(CDEFMessage cdefMessage) {
      super(cdefMessage);
      _action = cdefMessage.getInt();
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _outputMessages.add(new OutputMessage(cdefMessage));
         }
      }
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_action);
      cdefMessage.putInt(_outputMessages.size());
      for (OutputMessage obj : _outputMessages) {
         obj.encode(cdefMessage);
      }
   }

   public int getAction() { return _action; }
   public void setAction(int action) { _action = action; }

   public List<OutputMessage> getOutputMessages() { return _outputMessages; }
   public void setOutputMessages(List<OutputMessage> outputMessages) { _outputMessages = outputMessages; }
}
