//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class OutputDeviceRequest extends Message {
   private int _action;
   private List<Integer> _ids = new LinkedList<>();
   private List<OutputDevice> _outputDevices = new LinkedList<>();

   public OutputDeviceRequest() {
      super(FunctionCode.OutputDevice, 0);
   }

   public OutputDeviceRequest(CDEFMessage cdefMessage) {
      super(cdefMessage);
      _action = cdefMessage.getInt();
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _ids.add(cdefMessage.getInt());
         }
      }
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _outputDevices.add(new OutputDevice(cdefMessage));
         }
      }
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_action);
      cdefMessage.putInt(_ids.size());
      for (Integer obj : _ids) {
         cdefMessage.putInt(obj);
      }
      cdefMessage.putInt(_outputDevices.size());
      for (OutputDevice obj : _outputDevices) {
         obj.encode(cdefMessage);
      }
   }

   public OutputDeviceResponse createResponse() {
      OutputDeviceResponse response = new OutputDeviceResponse(getTransactionNumber());
      return response;
   }

   public int getAction() { return _action; }
   public void setAction(int action) { _action = action; }

   public List<Integer> getIds() { return _ids; }
   public void setIds(List<Integer> ids) { _ids = ids; }

   public List<OutputDevice> getOutputDevices() { return _outputDevices; }
   public void setOutputDevices(List<OutputDevice> outputDevices) { _outputDevices = outputDevices; }
}
