//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 28/04/2014 1:27:52 AM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class OutputMessageRequest extends Message {
   private int _action;
   private List<Integer> _ids = new LinkedList<>();
   private List<OutputMessage> _outputMessages = new LinkedList<>();

   public OutputMessageRequest() {
      super(FunctionCode.OutputMessage, 0);
   }

   public OutputMessageRequest(CDEFMessage cdefMessage) {
      super(cdefMessage);
      _action = cdefMessage.getInt();
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _ids.add(cdefMessage.getInt());
         }
      }
      {
         int c = cdefMessage.getInt();
         for (int i=0; i<c; i++) {
            _outputMessages.add(new OutputMessage(cdefMessage));
         }
      }
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_action);
      cdefMessage.putInt(_ids.size());
      for (Integer obj : _ids) {
         cdefMessage.putInt(obj);
      }
      cdefMessage.putInt(_outputMessages.size());
      for (OutputMessage obj : _outputMessages) {
         obj.encode(cdefMessage);
      }
   }

   public OutputMessageResponse createResponse() {
      OutputMessageResponse response = new OutputMessageResponse(getTransactionNumber());
      return response;
   }

   public int getAction() { return _action; }
   public void setAction(int action) { _action = action; }

   public List<Integer> getIds() { return _ids; }
   public void setIds(List<Integer> ids) { _ids = ids; }

   public List<OutputMessage> getOutputMessages() { return _outputMessages; }
   public void setOutputMessages(List<OutputMessage> outputMessages) { _outputMessages = outputMessages; }
}
