//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api.messages;

import hasoftware.api.FunctionCode;
import hasoftware.api.classes.*;
import hasoftware.api.Message;
import hasoftware.cdef.*;
import java.util.LinkedList;
import java.util.List;

public class PointRequest extends Message {
   private int _action;
   private int _nodeId;
   private String _address;

   public PointRequest() {
      super(FunctionCode.Point, 0);
   }

   public PointRequest(CDEFMessage cdefMessage) {
      super(cdefMessage);
      _action = cdefMessage.getInt();
      _nodeId = cdefMessage.getInt();
      _address = cdefMessage.getString();
   }

   @Override
   public void encode(CDEFMessage cdefMessage) {
      super.encode(cdefMessage);
      cdefMessage.putInt(_action);
      cdefMessage.putInt(_nodeId);
      cdefMessage.putString(_address);
   }

   public PointResponse createResponse() {
      PointResponse response = new PointResponse(getTransactionNumber());
      return response;
   }

   public int getAction() { return _action; }
   public void setAction(int action) { _action = action; }

   public int getNodeId() { return _nodeId; }
   public void setNodeId(int nodeId) { _nodeId = nodeId; }

   public String getAddress() { return _address; }
   public void setAddress(String address) { _address = address; }
}
