//
// DO NOT EDIT THIS FILE - CONSTRUCTED ON 11/04/2015 2:56:09 PM
//

package hasoftware.api;

import hasoftware.cdef.CDEFFunctionCode;

public class FunctionCode extends CDEFFunctionCode {
      public static final int Error = 0x0000;
      public static final int Heartbeat = 0x0001;
      public static final int Notify = 0x0002;
      public static final int InputMessage = 0x1000;
      public static final int OutputMessage = 0x1001;
      public static final int Login = 0x1002;
      public static final int OutputDevice = 0x1004;
      public static final int Location = 0x1005;
      public static final int Point = 0x1006;
      public static final int CurrentEvent = 0x1007;
}
