package hasoftware.server.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import hasoftware.server.data.Device;
import hasoftware.server.data.InputEvent;
import hasoftware.server.data.OutputDevice;
import hasoftware.server.data.OutputEvent;

/**
 * Class _DeviceType was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _DeviceType extends CayenneDataObject {

    public static final String CODE_PROPERTY = "code";
    public static final String DESCRIPTION_PROPERTY = "description";
    public static final String DEVICES_PROPERTY = "devices";
    public static final String INPUT_EVENTS_PROPERTY = "inputEvents";
    public static final String OUTPUT_DEVICES_PROPERTY = "outputDevices";
    public static final String OUTPUT_EVENTS_PROPERTY = "outputEvents";

    public static final String ID_PK_COLUMN = "ID";

    public void setCode(String code) {
        writeProperty(CODE_PROPERTY, code);
    }
    public String getCode() {
        return (String)readProperty(CODE_PROPERTY);
    }

    public void setDescription(String description) {
        writeProperty(DESCRIPTION_PROPERTY, description);
    }
    public String getDescription() {
        return (String)readProperty(DESCRIPTION_PROPERTY);
    }

    public void addToDevices(Device obj) {
        addToManyTarget(DEVICES_PROPERTY, obj, true);
    }
    public void removeFromDevices(Device obj) {
        removeToManyTarget(DEVICES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Device> getDevices() {
        return (List<Device>)readProperty(DEVICES_PROPERTY);
    }


    public void addToInputEvents(InputEvent obj) {
        addToManyTarget(INPUT_EVENTS_PROPERTY, obj, true);
    }
    public void removeFromInputEvents(InputEvent obj) {
        removeToManyTarget(INPUT_EVENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<InputEvent> getInputEvents() {
        return (List<InputEvent>)readProperty(INPUT_EVENTS_PROPERTY);
    }


    public void addToOutputDevices(OutputDevice obj) {
        addToManyTarget(OUTPUT_DEVICES_PROPERTY, obj, true);
    }
    public void removeFromOutputDevices(OutputDevice obj) {
        removeToManyTarget(OUTPUT_DEVICES_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<OutputDevice> getOutputDevices() {
        return (List<OutputDevice>)readProperty(OUTPUT_DEVICES_PROPERTY);
    }


    public void addToOutputEvents(OutputEvent obj) {
        addToManyTarget(OUTPUT_EVENTS_PROPERTY, obj, true);
    }
    public void removeFromOutputEvents(OutputEvent obj) {
        removeToManyTarget(OUTPUT_EVENTS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<OutputEvent> getOutputEvents() {
        return (List<OutputEvent>)readProperty(OUTPUT_EVENTS_PROPERTY);
    }


}
