package hasoftware.server.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import hasoftware.server.data.Permission;
import hasoftware.server.data.User;

/**
 * Class _Group was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Group extends CayenneDataObject {

    public static final String CREATED_ON_PROPERTY = "createdOn";
    public static final String NAME_PROPERTY = "name";
    public static final String UPDATED_ON_PROPERTY = "updatedOn";
    public static final String PERMISSIONS_PROPERTY = "permissions";
    public static final String USERS_PROPERTY = "users";

    public static final String ID_PK_COLUMN = "ID";

    public void setCreatedOn(Long createdOn) {
        writeProperty(CREATED_ON_PROPERTY, createdOn);
    }
    public Long getCreatedOn() {
        return (Long)readProperty(CREATED_ON_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setUpdatedOn(Long updatedOn) {
        writeProperty(UPDATED_ON_PROPERTY, updatedOn);
    }
    public Long getUpdatedOn() {
        return (Long)readProperty(UPDATED_ON_PROPERTY);
    }

    public void addToPermissions(Permission obj) {
        addToManyTarget(PERMISSIONS_PROPERTY, obj, true);
    }
    public void removeFromPermissions(Permission obj) {
        removeToManyTarget(PERMISSIONS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Permission> getPermissions() {
        return (List<Permission>)readProperty(PERMISSIONS_PROPERTY);
    }


    public void addToUsers(User obj) {
        addToManyTarget(USERS_PROPERTY, obj, true);
    }
    public void removeFromUsers(User obj) {
        removeToManyTarget(USERS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<User> getUsers() {
        return (List<User>)readProperty(USERS_PROPERTY);
    }


}
