package hasoftware.server.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import hasoftware.server.data.Device;
import hasoftware.server.data.Node;

/**
 * Class _Node was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Node extends CayenneDataObject {

    public static final String CREATED_ON_PROPERTY = "createdOn";
    public static final String NAME_PROPERTY = "name";
    public static final String UPDATED_ON_PROPERTY = "updatedOn";
    public static final String CHILDREN_PROPERTY = "children";
    public static final String PARENT_PROPERTY = "parent";
    public static final String UNTITLED_REL_PROPERTY = "untitledRel";

    public static final String ID_PK_COLUMN = "ID";

    public void setCreatedOn(Long createdOn) {
        writeProperty(CREATED_ON_PROPERTY, createdOn);
    }
    public Long getCreatedOn() {
        return (Long)readProperty(CREATED_ON_PROPERTY);
    }

    public void setName(String name) {
        writeProperty(NAME_PROPERTY, name);
    }
    public String getName() {
        return (String)readProperty(NAME_PROPERTY);
    }

    public void setUpdatedOn(Long updatedOn) {
        writeProperty(UPDATED_ON_PROPERTY, updatedOn);
    }
    public Long getUpdatedOn() {
        return (Long)readProperty(UPDATED_ON_PROPERTY);
    }

    public void addToChildren(Node obj) {
        addToManyTarget(CHILDREN_PROPERTY, obj, true);
    }
    public void removeFromChildren(Node obj) {
        removeToManyTarget(CHILDREN_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Node> getChildren() {
        return (List<Node>)readProperty(CHILDREN_PROPERTY);
    }


    public void setParent(Node parent) {
        setToOneTarget(PARENT_PROPERTY, parent, true);
    }

    public Node getParent() {
        return (Node)readProperty(PARENT_PROPERTY);
    }


    public void addToUntitledRel(Device obj) {
        addToManyTarget(UNTITLED_REL_PROPERTY, obj, true);
    }
    public void removeFromUntitledRel(Device obj) {
        removeToManyTarget(UNTITLED_REL_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Device> getUntitledRel() {
        return (List<Device>)readProperty(UNTITLED_REL_PROPERTY);
    }


}
