package hasoftware.server.data.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import hasoftware.server.data.Group;

/**
 * Class _User was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _User extends CayenneDataObject {

    public static final String CREATED_ON_PROPERTY = "createdOn";
    public static final String FIRST_NAME_PROPERTY = "firstName";
    public static final String LAST_NAME_PROPERTY = "lastName";
    public static final String PASSWORD_PROPERTY = "password";
    public static final String UPDATED_ON_PROPERTY = "updatedOn";
    public static final String USERNAME_PROPERTY = "username";
    public static final String GROUPS_PROPERTY = "groups";

    public static final String ID_PK_COLUMN = "ID";

    public void setCreatedOn(Long createdOn) {
        writeProperty(CREATED_ON_PROPERTY, createdOn);
    }
    public Long getCreatedOn() {
        return (Long)readProperty(CREATED_ON_PROPERTY);
    }

    public void setFirstName(String firstName) {
        writeProperty(FIRST_NAME_PROPERTY, firstName);
    }
    public String getFirstName() {
        return (String)readProperty(FIRST_NAME_PROPERTY);
    }

    public void setLastName(String lastName) {
        writeProperty(LAST_NAME_PROPERTY, lastName);
    }
    public String getLastName() {
        return (String)readProperty(LAST_NAME_PROPERTY);
    }

    public void setPassword(String password) {
        writeProperty(PASSWORD_PROPERTY, password);
    }
    public String getPassword() {
        return (String)readProperty(PASSWORD_PROPERTY);
    }

    public void setUpdatedOn(Long updatedOn) {
        writeProperty(UPDATED_ON_PROPERTY, updatedOn);
    }
    public Long getUpdatedOn() {
        return (Long)readProperty(UPDATED_ON_PROPERTY);
    }

    public void setUsername(String username) {
        writeProperty(USERNAME_PROPERTY, username);
    }
    public String getUsername() {
        return (String)readProperty(USERNAME_PROPERTY);
    }

    public void addToGroups(Group obj) {
        addToManyTarget(GROUPS_PROPERTY, obj, true);
    }
    public void removeFromGroups(Group obj) {
        removeToManyTarget(GROUPS_PROPERTY, obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Group> getGroups() {
        return (List<Group>)readProperty(GROUPS_PROPERTY);
    }


}
